# Generated by Django 3.2.4 on 2021-06-19 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
                ('name', models.CharField(max_length=100)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='tgbot.chat', verbose_name='Группа')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='money.category', verbose_name='Категория')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='tgbot.chat', verbose_name='Группа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='tgbot.user', verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
